# Generated by Django 5.2.1 on 2025-05-21 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_movie_tmdb_id_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tmdb_id',
        ),
    ]
